exports.up = function (knex, Promise) {
    return knex.schema.createTable('deals', function (table) {
        table.string('deal_id').primary()
        table.string('deal_title', 30).notNullable()
        table.string('deal_type_id').references('deals_type.deal_type_id')
        table.string('deal_category_id').references('deal_categories.deal_category_id')
        table.string('merchant_id').references('merchants.merchant_id')
        table.string('merchant_outlet_id').references('merchant_outlets.merchant_outlet_id')
        table.string('tag_id').references('tags.tag_id')
        table.string('cta_button_text', 55).notNullable()
        table.datetime('promotion_start_at').notNullable()
        table.datetime('promotion_end_at').notNullable()
        table.string('deal_image', 255).notNullable()
        table.enum('container_expiry_type', [1, 2, 3, 4]).defaultTo(4)
        table.timestamp('container_expiry_at')
        table.string('container_timer_image', 255)
        table.enum('arrival_element', [1, 2, 3]).defaultTo(3)
        table.string('push_notification_message', 255)
        table.enum('push_notification_condition', [1, 2, 3, 4]).defaultTo(4)
        table.string('push_notification_location')
        table.enum('voucher_type', [1, 2]).defaultTo(1)
        table.enum('voucher_expiry_type', [1, 2, 3]).defaultTo(1)
        table.integer('voucher_expiry_time', 10)
        table.integer('grab_limit', 20)
        table.integer('reedem_limit', 20)
        table.enum('targeting_option', [1, 2, 3]).defaultTo(1)
        table.integer('targeting_condition', 20)
        table.integer('targeting_customer_count', 20)
        table.integer('targeting_day_month', 20)
        table.integer('targeting_value', 20)
        table.integer('targeting_msisdn', 20)
        table.enum('save_status', [1, 2, 3]).defaultTo(2)
        table.enum('status', ['Unchecked', 'Checked']).defaultTo('Unchecked')
        table.string('created_by').references('users.user_id')
        table.string('updated_by').references('users.user_id')
        table.timestamps()
    })
}

exports.down = function (knex, Promise) {
    return knex.schema.dropTableIfExists('deals')
}